name:            env
version:         0.1.0
synopsis:        CI test
description:     Dummy project to test CI setup and cache.
license:         BSD3
author:          Bruno Damour <bruno@ruomad.net>
maintainer:      Bruno Damour <bruno@ruomad.net>
copyright:       (c) 2013-2022 Bruno Damour
category:        Tools
build-type:      Simple

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 1.2.4
  - bytestring >= 0.10.8
  - cassava >= 0.5.1
  - conduit >= 1.3
  - containers >= 0.5.11
  - cubicspline >= 0.1.2
  - directory >= 1.3
  - monad-logger >= 0.3
  - persistent >= 2.9
  - regex >= 1.1
  - regex-tdfa
  - resourcet >= 1.2
  - scientific >= 0.3.5
  - text >= 1.2.3
  - time >= 1.8
  - transformers >= 0.5
  - unordered-containers >= 0.2
  - utf8-string
  - vector >= 0.12
  - xml-conduit >= 1.8
  - xml-types >= 0.3.6
  - zip >= 1.0
  # for executables
  - optparse-applicative >= 0.14.2
  - ansi-wl-pprint >= 0.6.8
  - persistent-sqlite >= 2.9
  - persistent-postgresql >= 2.9

ghc-options:  -O3 -fexcess-precision -optc-O3

executables:
  test:
    main:	Main.hs
