# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Local bin path
local-bin-path: /usr/local/bin

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: snapshot.yaml

# Local packages, usually specified by relative directory name
packages:
  - .
